/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema.ticketing.system;

import static cinema.ticketing.system.showTime.id;
import java.io.BufferedReader;
import java.io.*;
import java.io.FileReader;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author sudishrestha
 */
public class PurchaseTicket extends javax.swing.JFrame {

    /**
     * Creates new form PurchaseTicket
     */
    String[][] lists = new String[20][3];
int std,adl,chl = 0;
    public PurchaseTicket() {
        initComponents();
        setSize(742, 440);
        setTitle("Cinema Ticket Machine");
        getMovie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Welcome To Cinema Ticketing System");

        jButton1.setText("List Movies");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Show Times");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Purchase Ticket");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Show Reciept");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("Movie : ");

        jLabel6.setText("Time");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Time", "8:00", "11:00", "14:00", "17:00", "20:00" }));

        jLabel7.setText("Total :   €");

        jLabel8.setText("0");

        jButton6.setText("Purchase");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel9.setText("Category");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel10.setText("Student ( € 4.00 )");

        jLabel11.setText("Adult ( € 5.00)");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel12.setText("Children (€ 3.00)");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jLabel13.setText("Total No of Ticket : ");

        jLabel14.setText("0");

        jLabel3.setText("HAll");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Hall", "A", "B", "C", "D", "E" }));

        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(118, 118, 118)
                                .addComponent(jLabel14)
                                .addGap(176, 176, 176))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel10)))
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(307, 307, 307)
                                .addComponent(jLabel9)
                                .addGap(42, 42, 42)))
                        .addGap(126, 126, 126)
                        .addComponent(jLabel12)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(337, 337, 337))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(23, 23, 23)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(35, 35, 35)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(44, 44, 44)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainForm mf = new MainForm();
        mf.show();
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void getMovie() {
        try (BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\sudishrestha\\Documents\\NetBeansProjects\\Cinema Ticketing System\\src\\cinema\\ticketing\\system\\Movies.txt"))) {
            StringBuilder sb = new StringBuilder();
            String line = br.readLine();
            int i = 0;
            while (line != null) {
                sb.append(line);

                String[] parts = new String[3];
                if (line != null) {
                    line = line.replace(",", "");
                    parts = line.split("-");
                }

                if (parts[0] != null || parts[1] != null || parts[2] != null) {
                    lists[i][0] = parts[0];
                    lists[i][1] = parts[1];

                    lists[i][2] = parts[2];
                }
                line = br.readLine();
                i++;
            }
            String everything = sb.toString();
            jComboBox1.addItem("Select Movie");
            for (int j = 0; j < 20; j++) {
                if (lists[j][0] != null || lists[j][1] != null) {
                    // System.out.println(lists[j][i]);
                    jComboBox1.addItem(lists[j][1]);
                    System.out.println(lists[j][0] + "***************" + lists[j][1]);

                    //jTextArea1.setText(jTextArea1.getText().trim() + "\n" + lists[j][0] + "\t" + lists[j][1] + "\t\t\t\t" + lists[j][2] + "\r\n");
                }
            }

        } catch (Exception E) {
            //JOptionPane.showMessageDialog(null, E);
        }
    }

    public void getNames() {
        try (BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\sudishrestha\\Documents\\NetBeansProjects\\Cinema Ticketing System\\src\\cinema\\ticketing\\system\\Movies.txt"))) {
            StringBuilder sb = new StringBuilder();
            String line = br.readLine();
            int i = 0;
            while (line != null) {
                sb.append(line);

                System.out.println(line);

                String[] parts = new String[3];
                if (line != null) {
                    line = line.replace(",", "");
                    parts = line.split("-");
                }
                if (line == null) {
                    break;
                }
                if (parts[0] != null || parts[1] != null || parts[2] != null) {
                    lists[i][0] = parts[0];
                    lists[i][1] = parts[1];
                    lists[i][2] = parts[2];
                    // System.out.println(lists[i][0]);
                }
                line = br.readLine();
                i++;
            }
            String everything = sb.toString();
            for (int j = 0; j < 20; j++) {
                if (lists[j][0].trim().equals(id)) {

                    System.out.println(lists[j][1] + "***************" + lists[j][2]);
                  //  jLabel3.setText(lists[j][1]);
                    //jLabel5.setText(lists[j][2]);

                }
            }

        } catch (Exception E) {
            //   JOptionPane.showMessageDialog(null, E);
        }
    }

    public void getData() {
        try (BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\sudishrestha\\Documents\\NetBeansProjects\\Cinema Ticketing System\\src\\cinema\\ticketing\\system\\movieTime.txt"))) {
            StringBuilder sb = new StringBuilder();
            String line = br.readLine();

            while (line != null) {
                sb.append(line);
                String[] part = new String[6];
                String[] part1 = new String[2];
                //System.out.println(line);
                part = line.split("-");
                if (part[0].trim().equals(id)) {
                    // System.out.println(line);
                    for (int l = 1; l < 6; l++) {
                        part1 = part[l].split(",");
                        if (!part1[1].trim().equals("N")) {
                            // avail = avail + "\n\t" + part1[0] + " \t\t\t                      " + part1[1] + lins;
                        }
                    }

                }
                line = br.readLine();

            }  //jTextArea1.setText(jTextArea1.getText() + "\n" + avail);
        } catch (Exception Ec) {

        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        getData();
        if (jTextField1.getText().trim().equals("")) {
            showTime st = new showTime();
            st.show();
            this.hide();
        } else {
            int k = 0;
            for (int i = 0; i < 20; i++) {
                System.out.println(lists[i][0]);
            }
            for (int i = 0; i < 20; i++) {
                if (lists[i][0] != null) {
                    if (lists[i][0].trim().equals(jTextField1.getText().trim())) {
                        k = 1;
                    }
                }
            }
            if (k == 1) {
                showTime st = new showTime(jTextField1.getText().trim());
                st.show();
                this.hide();
            } else {
                JOptionPane.showMessageDialog(null, "Please enter Valid ID!!!");
            }
        }

        getNames();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem().toString().trim().equals("Select Movie")) {
            JOptionPane.showMessageDialog(null, "Please select the movie!!!");
        } else if (jComboBox2.getSelectedItem().toString().trim().equals("Select Time")) {
            JOptionPane.showMessageDialog(null, "Please select the Time!!!");
        } else if (jComboBox3.getSelectedItem().toString().trim().equals("Select Hall")) {
            JOptionPane.showMessageDialog(null, "Please select the Hall!!!");
        } else if (jLabel14.getText().trim().equals("0")) {
            JOptionPane.showMessageDialog(null, "Select the no of Ticket!!!");
        } else {
            System.out.println(jComboBox1.getSelectedItem().toString());
            System.out.println(jComboBox2.getSelectedItem().toString());
            System.out.println(jComboBox3.getSelectedItem().toString());
            System.out.println(jComboBox4.getSelectedItem().toString());
            System.out.println(jComboBox5.getSelectedItem().toString());
            System.out.println(jComboBox6.getSelectedItem().toString());
            System.out.println(jLabel14.getText().trim());
            System.out.println(jLabel8.getText().trim());

            try {

                String content = jComboBox1.getSelectedItem().toString()
                        + "\n" + jComboBox2.getSelectedItem().toString()
                        + "\n" + jComboBox3.getSelectedItem().toString()
                        + "\n" + jComboBox4.getSelectedItem().toString()
                        + "\n" + jComboBox5.getSelectedItem().toString()
                        + "\n" + jComboBox6.getSelectedItem().toString()
                        + "\n" + jLabel14.getText().trim()
                        + "\n" + jLabel8.getText().trim();

                File file = new File("C:\\Users\\sudishrestha\\Documents\\NetBeansProjects\\Cinema Ticketing System\\src\\cinema\\ticketing\\system\\TempData.txt");

                // if file doesnt exists, then create it
                if (!file.exists()) {
                    file.createNewFile();
                }

                FileWriter fw = new FileWriter(file.getAbsoluteFile());
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(content);
                bw.close();

                System.out.println("Done");

            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        
        int sum = Integer.parseInt(jLabel14.getText().trim()) + Integer.parseInt(jComboBox4.getSelectedItem().toString().trim())-std;
        jLabel14.setText(sum + "");
       
       int te = std * 4;
        int sum2 = Integer.parseInt(jLabel8.getText().trim()) + Integer.parseInt(jComboBox4.getSelectedItem().toString().trim()) * 4 - te;
        jLabel8.setText(sum2 + "");
         std = Integer.parseInt(jComboBox4.getSelectedItem().toString().trim());
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Reciept rcp = new Reciept();
        rcp.show();
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        int sum = Integer.parseInt(jLabel14.getText().trim()) + Integer.parseInt(jComboBox5.getSelectedItem().toString().trim()) - adl;
        jLabel14.setText(sum + "");
        int te = adl * 5;
        
        int sum2 = Integer.parseInt(jLabel8.getText().trim()) + Integer.parseInt(jComboBox5.getSelectedItem().toString().trim()) * 5 - te;
        jLabel8.setText(sum2 + "");
        adl = Integer.parseInt(jComboBox5.getSelectedItem().toString().trim());
        
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        
        int sum = Integer.parseInt(jLabel14.getText().trim()) + Integer.parseInt(jComboBox6.getSelectedItem().toString().trim()) - chl;
        jLabel14.setText(sum + "");
       int te = chl *3;
        int sum2 = Integer.parseInt(jLabel8.getText().trim()) + Integer.parseInt(jComboBox6.getSelectedItem().toString().trim()) * 3 - te;
        jLabel8.setText(sum2 + "");
         chl =Integer.parseInt(jComboBox6.getSelectedItem().toString().trim());
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       PurchaseTicket pct = new PurchaseTicket();
       pct.show();
       this.hide();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseTicket().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
